export function renderSkills() {
  return <div>
    <p>The following is a list of skills and technologies I have worked with, and am familiar with.</p>
    <p>
      JavaScript,
      Node.js (since 0.4),
      Express,
      Koa,
      Angular (1 and 2),
      React,
      Redux/Flux,
      RethinkDB,
      MongoDB,
      Cassandra,
      ElasticSearch,
      Microsoft SQL Server (MS-SQL, T-SQL, Versions 6-2008),
      Oracle,
      FirebirdSQL,
      PostgreSQL,
      MySQL,
      Stored Procedures,
      Triggers,
      Classic ASP (Jscript, VBScript),
      C# (ASP.Net, ASP.Net MVC, Mono, Winforms, Webforms, Server Controls, Web Controls, WCF, Web Services, Windows Services),
      VisualBasic.Net (VB.Net), 
      Visual Basic,
      HTML,
      HTML5,
      CSS,
      CSS3,
      DHTML,
      Ajax,
      Comet,
      Web Sockets,
      Socket.io,
      Microsoft Ajax Toolkit,
      jQuery,
      jQueryUI,
      Twitter Bootstrap (twbs),
      Prototype JS,
      Scriptaculous,
      ExtJS,
      Flash,
      Actionscript,
      JSON,
      XML,
      Windows,
      Linux,
      BSD,
      Mac OS X,
      Internet Information Server (IIS), 
      NginX, 
      Apache  
    </p>
  </div>;
}